pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    xcodebuild -scheme UserPortfolio \
                               -workspace UserPortfolio.xcworkspace \
                               -sdk iphonesimulator \
                               -configuration Debug build
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    xcodebuild test -scheme UserPortfolio \
                                    -workspace UserPortfolio.xcworkspace \
                                    -sdk iphonesimulator \
                                    -configuration Debug
                '''
            }
        }
    }
}
