pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                xcodebuild -scheme UserPortfolio \
                           -project UserPortfolio/UserPortfolio.xcodeproj \
                           -sdk iphonesimulator \
                           -configuration Debug build
                '''
            }
        }
        stage('Test in Parallel') {
            parallel {
                stage('Test on iPhone 16') {
                    steps {
                        sh '''
                        xcodebuild test -scheme UserPortfolio \
                                        -project UserPortfolio/UserPortfolio.xcodeproj \
                                        -sdk iphonesimulator \
                                        -configuration Debug \
                                        -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.3.1'
                        '''
                    }
                }
                stage('Test on iPad mini (A17 pro)') {
                    steps {
                        sh '''
                        xcodebuild test -scheme UserPortfolio \
                                        -project UserPortfolio/UserPortfolio.xcodeproj \
                                        -sdk iphonesimulator \
                                        -configuration Debug \
                                        -destination 'platform=iOS Simulator,name=iPad mini (A17 pro),OS=18.3.1'
                        '''
                    }
                }
                stage('Test on iPad (10th generation)') {
                    steps {
                        sh '''
                        xcodebuild test -scheme UserPortfolio \
                                        -project UserPortfolio/UserPortfolio.xcodeproj \
                                        -sdk iphonesimulator \
                                        -configuration Debug \
                                        -destination 'platform=iOS Simulator,name=iPad (10th generation),OS=18.3.1'
                        '''
                    }
                }
            }
        }
    }
}
